LOGGING_LEVEL: 'INFO'
LOGGING_FORMAT: '%(asctime)-15s | %(levelname)s | %(filename)s | %(lineno)d: %(message)s'

WEB_HOST: '127.0.0.1'
WEB_PORT: 8000

BASE_URL: 'https://currate.ru/api/'
API_KEY: '2b816399d134da99b19b3cc54940b848'
REQUEST_SCHEDULER_TIME_INTERVAL_SECONDS: 10

KAFKA_BROKER: "127.0.0.1:9093"
SRC_DATA_TOPIC: "src-data"

PROMETHEUS_PORT: 7000